//
//  QuestionsRouter.swift
//  Interlude
//
//  Created by Gerson Noboa on 05/11/2019.
//  Copyright (c) 2019 Heavenlapse. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol QuestionsRouterProtocol {
  //func routeToSomewhere()
}

final class QuestionsRouter: QuestionsRouterProtocol {
    //func routeToSomewhere(segue: UIStoryboardSegue?) { }
}
