//
//  QuestionsRouter.swift
//  Interlude
//
//  Created by Gerson Noboa on 05/11/2019.
//  Copyright (c) 2019 Heavenlapse. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol QuestionsRouterProtocol {
    func navigateToAnswer()
    func passDataToNextScene(using segue: UIStoryboardSegue)
}

final class QuestionsRouter: QuestionsRouterProtocol {
    weak var viewController: QuestionsViewController?
    
    init(viewController: QuestionsViewController?) {
        self.viewController = viewController
    }
    
    func navigateToAnswer() {
        viewController?.performSegue(withIdentifier: Segues.questionsToAnswer, sender: nil)
    }
    
    func passDataToNextScene(using segue: UIStoryboardSegue) {
        if segue.identifier == Segues.questionsToAnswer {
            passDataToAnswer(using: segue)
        }
    }
    
    private func passDataToAnswer(using segue: UIStoryboardSegue) {
        let source = segue.source as! QuestionsViewController
        let destionation = segue.destination as! AnswerViewController
        
        guard let selectedIndexPath = source.tableView.indexPathForSelectedRow else { return }
        
        let request = Answer.Request(index: selectedIndexPath.row)
        destionation.request = request
    }
}
